### ISSUE TITLE
elod:website property doesn't exist in the elod ontology

### ISSUE THREAD

**Issue by mogaio** [YourDataStories/ontology#49]
The elod:website property doesn't exist in elod ontology, we should replace it with elod:organizationWebsite instead.

https://github.com/LinkedEcon/LinkedEconomyOntology-ELOD/blob/7ec6458de2386ec873b676092dcfa4d6c080d288/Diavgeia/diavgeia_ontology.owl

**Comment by Polymathronic** [comment]
This is not being used in pilots 1 and 2. If you are the one using it, then please assign the issue to yourself.

**Comment by mogaio** [comment]
It's fixed in our model but I shared it with you since it's mentioned in the data model (deliverable 3.3) and pliots (1,2) might use it later.

**Comment by Polymathronic** [comment]
OK, thanks.

@vafopoulos @giorgosvaf Is this property documented anywhere else?

By the way, there is also foaf:homepage. Are the semantics any different?

**Comment by giorgosvaf** [comment]
As far as i see, conceptually, elod:organizationWebsite links an Organization to a website and foaf:homepage links to the home page of the website.
So we created elod:organizationWebsite in order to describe the whole website as an entity.
I updated mastersheet with the property,
https://docs.google.com/spreadsheets/d/1xMiTAk7mXhGPnSU4-qspiYaN15ur4v3J0lU8qYODtzk/edit#gid=481927591 

Uros what is your suggestion on this, is elod:organizationWebsite redundant?

**Comment by giorgosvaf** [comment]
Also, forget about elod:website property.

And from now on please follow this document,
https://docs.google.com/spreadsheets/d/1xMiTAk7mXhGPnSU4-qspiYaN15ur4v3J0lU8qYODtzk/edit#gid=481927591

**Comment by Polymathronic** [comment]
If there is a really good use case for it (I can't think of a scenario, but you probably know why you introduced it), then there is no need to remove it. However, I see it's a datatype property, and when someone talks entities, I tend to think in terms of object properties.

@mogaio I would probably go with `foaf:homepage` just to be on the safe side, unless @giorgosvaf thinks otherwise.

**Comment by giorgosvaf** [comment]
Yes you are right, i had something else on my mind(that's why i said entity) so forget about it. 
We will not remove elod:organizationWebsite that's for sure.

@mogaio You could use foaf:homepage as @Polymathronic said.

**Comment by mogaio** [comment]
okay sure.
