### ISSUE TITLE
Pilot 3 OWL File Corrections.

### ISSUE THREAD

**Issue by giorgosvaf** [YourDataStories/ontology#59]
Please check the following issues on your OWL file carefully,
https://github.com/YourDataStories/ontology/blob/pilot3/pilot3/pilot3ontology.owl.
1. All of your properties should have Domain & Range Class, for example dct:description does not have any Domain Class.
2. Remove from your OWL file the classes/properties that you don't use in your dataset( for example you don't have elod:ExpenseApprovalItem class).
3. Check the relations among classes and the relations among properties. For example foaf:Person **is subclass of** foaf:Agent and pc:Tender **is not subclass of** gr:Offering.
4. Why do you use pc:percentage to Class Hierarchy?

**Comment by Islhas** [comment]
I went throught the OWL file to double check your point.
for point 1:
dct:description is described in the lines between 379 - 384 and have domain and range.

2: elod:ExpenseApprovalItem is in the document because we thought that we might need it later but we can remove it and update the OWL then.

3:  foaf:Person is subclass of foaf:Agent please check the FOAF Vocabulary Specification http://xmlns.com/foaf/spec/20140114.rdf
you can find it in the lines between 54 - 71 

pc:Tender is subclass of gr:Offering please check the Public Contracts Ontology https://github.com/opendatacz/public-contracts-ontology/blob/master/public-contracts.rdf
you can find it in the lines between 104 - 111

4: pc:percentage is the range of the functional property criterionWeight as described in the Public Contracts Ontology 
https://github.com/opendatacz/public-contracts-ontology/blob/master/public-contracts.rdf
you can find it in the lines between 284 - 293

**Comment by giorgosvaf** [comment]
Thanks for your comments!

First of all, in order to understand my comments, please open the OWL file using Protege as I do.
1. dct:description(an example that I mentioned) do have domain and range but you have as domain class "elod:Subsidy" which is not defined in Classes(I can not see it in Protege), so if you go to datatype properties you will not see any domain class to be specified for this property. But, except from that, you don't use elod:Subsidy Class in your data, so you have to use pc:Contract instead of that, which as far as i can see from your pilot3 graph, is the domain class of dct:description.
   Please check and the other properties again and also the fact that you have specified some properties as Annotation properties which are not, for example gr:hasCurrencyValue. 
2. Yes it would be better.
3. If you see my comment on foaf:Person carefully that's what i'm saying... foaf:Person **is subclass of foaf:Agent** but your OWL does not include it.
   About pc:Tender & gr:Offering you are right!
4. Ok I see it but it's not a class! it's a datatype and if you leave it that way, without specifying it in your OWL that it is a datatype, Protege will present it as Class.
   So I suggest to add the following in your OWL file in order to represent it as a datatype,
   **rdfs:Datatype rdf:about="http://purl.org/procurement/public-contracts-datatypes#percentage"**
